version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_coffee_container
    restart: always
    environment:
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_PASSWORD: "${postgres_pass}"
    ports:
      - "${postgres_host}"
    volumes:
      - type: volume
        source: my_db_files
        target: /var/lib/postgres
  adminer:
    image: adminer
    container_name: adminer_coffee_container
    restart: always
    ports: 
     - "${adminer_port}"
volumes:
  my_db_files: