version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_coffee_container
    restart: always
    environment:
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_PASSWORD: "${postgres_pass}"
      POSTGRES_DB: coffee_cartel_db
    ports:
      - "${postgres_port}:5432"
    volumes:
      - my_db_files:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_coffee_container
    restart: always
    ports: 
      - "${adminer_port}:8080"

volumes:
  my_db_files:
    driver: local
