AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying Lambda functions and related resources.

Parameters:
  S3BucketName:
    Type: String
    Default: 'coffee-cartel-bucket'
    Description: Name of the existing S3 bucket that triggers the Lambda function

  SSMParameterName:
    Type: String
    Default: 'coffee_cartel_redshift_settings'
    Description: Name of the SSM parameter that contains Redshift connection settings

  LambdaCodeBucket:
    Type: String
    Default: 'cc-lambda-function-bucket'  # Bucket created by GitHub Actions
    Description: Name of the S3 bucket that contains the Lambda code

  SQSQueueArn:
    Type: String
    Default: 'arn:aws:sqs:eu-west-1:339713081862:CC-Q'
    Description: ARN of the existing SQS queue

Resources:
  ExtractTransformLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::339713081862:role/lambda-execution-role
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: extract-transform-lambda.zip  # Ensure this key exists in the bucket
      Runtime: python3.11
      Timeout: 900
      MemorySize: 128
      Environment:
        Variables:
          SQS_QUEUE_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/CC-Q
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: !Sub "/aws/lambda/${AWS::StackName}-${AWS::Region}-${AWS::StackName}-ExtractTransformLambdaFunction"

  LoadLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::339713081862:role/lambda-execution-role
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: load-lambda.zip  # Ensure this key exists in the bucket
      Runtime: python3.11
      Timeout: 900
      MemorySize: 128
      Environment:
        Variables:
          SSM_PARAMETER_NAME: !Ref SSMParameterName
      VpcConfig:
        SubnetIds:
          - subnet-011e49d2c53653df9
        SecurityGroupIds:
          - sg-05347bb4c6b2f7d31
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: !Sub "/aws/lambda/${AWS::StackName}-${AWS::Region}-${AWS::StackName}-LoadLambdaFunction"

  LambdaPermissionForS3ExtractTransform:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ExtractTransformLambdaFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub arn:aws:s3:::${S3BucketName}

  LambdaPermissionForSQS:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LoadLambdaFunction
      Principal: sqs.amazonaws.com
      SourceArn: !Ref SQSQueueArn

  S3BucketNotification:
    Type: Custom::S3BucketNotification
    Properties:
      ServiceToken: !ImportValue S3NotificationFunctionArn  # ARN of a Lambda function to handle S3 bucket notifications
      Bucket: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: csv
            Function: !GetAtt ExtractTransformLambdaFunction.Arn

  SQSQueueTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !Ref SQSQueueArn
      FunctionName: !Ref LoadLambdaFunction
      Enabled: true

Outputs:
  ExtractTransformLambdaFunctionArn:
    Description: ARN of the Extract-Transform Lambda function
    Value: !GetAtt ExtractTransformLambdaFunction.Arn

  LoadLambdaFunctionArn:
    Description: ARN of the Load Lambda function
    Value: !GetAtt LoadLambdaFunction.Arn

  SSMParameterName:
    Description: Name of the SSM parameter containing Redshift settings
    Value: !Ref SSMParameterName
