AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Lambda function, S3 bucket, and connect to an existing Redshift cluster using SSM Parameter Store

Parameters:
  SSMParameterName:
    Type: String
    Default: 'coffee_cartel_redshift_settings'
    Description: Name of the SSM parameter that contains Redshift connection settings

Resources:
  MyTriggerS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: coffee-cartel-bucket2311222

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::339713081862:role/lambda-execution-role  # Use the existing IAM role ARN here
      Code:
        S3Bucket: lol123lol
        S3Key: coffee-cartel-2_2.zip  # Ensure this matches the actual zip file name in your bucket
      Runtime: python3.11
      Timeout: 300
      Environment:
        Variables:
          SSM_PARAMETER_NAME: !Ref SSMParameterName

  LambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    DependsOn: MyLambdaFunction
    Properties:
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt MyTriggerS3Bucket.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt MyLambdaFunction.Arn

  SSMParameterName:
    Description: Name of the SSM parameter containing Redshift settings
    Value: !Ref SSMParameterName