name: Deploy via CloudFormation

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}} 
          aws-region: eu-west-1

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
        shell: pwsh

      - name: Zip Lambda function using PowerShell
        run: |
          Compress-Archive -Path .\my-lambda-function\* -DestinationPath coffee-cartel-2_2.zip
        shell: pwsh

      - name: Create S3 Bucket
        run: |
          aws s3 mb s3://cc-lambda-function-bucket --region eu-west-1
        shell: pwsh

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp coffee-cartel-2_2.zip s3://cc-lambda-function-bucket/
        shell: pwsh

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy `
            --template-file template.yaml `
            --stack-name my-stack `
            --parameter-overrides `
              S3Bucket=cc-lambda-function-bucket `
              S3BucketName=coffee-cartel-drop-bucket `
              SSMParameterName=coffee_cartel_redshift_settings `
            --capabilities CAPABILITY_NAMED_IAM
        shell: pwsh
