name: Deploy via CloudFormation

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}} 
          aws-region: eu-west-1

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Zip Lambda function
        run: |
          cd my-lambda-function
          zip -r coffee-cartel-2_2.zip * .[^.] .??*

      - name: Create S3 Bucket if not exists
        id: create_s3_bucket
        run: |
          if aws s3 ls "s3://cc-lambda-function-bucket" 2>&1 | grep -q 'NoSuchBucket'; then
            aws s3 mb s3://cc-lambda-function-bucket --region eu-west-1
          else
            echo "Bucket already exists."
          fi

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp my-lambda-function/coffee-cartel-2_2.zip s3://cc-lambda-function-bucket/

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name my-stack \
            --parameter-overrides \
              S3Bucket=cc-lambda-function-bucket \
              S3BucketName=coffee-cartel-bucket222222 \
              SSMParameterName=coffee_cartel_redshift_settings \
            --capabilities CAPABILITY_NAMED_IAM
