name: Deploy via CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda function
        run: |
          cd my-lambda-function
          zip -r lambda-package.zip .

      - name: Create S3 Bucket
        id: create_s3_bucket
        run: |
          aws s3 mb s3://cc-lambda-function-bucket --region eu-west-1

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp my-lambda-function/lambda-package.zip s3://cc-lambda-function-bucket/

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name my-stack \
            --parameter-overrides \
              S3BucketName=cc-lambda-function-bucket \
              SSMParameterName=coffee_cartel_redshift_settings \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Clean up Lambda package
        run: rm -rf cc-lambda-function/lambda-package.zip
